version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  custom: #'%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(lineno)d - %(message)s'
    format: '[%(levelname)s | %(asctime)s | %(module)s(L%(lineno)d)] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  formatter_access:
    format: '[%(asctime)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    level: INFO
    class: logging.StreamHandler
    formatter: custom
    stream: ext://sys.stdout
  info_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: custom
    when: 'midnight'
    interval: 1
    backupCount: 7
    encoding: 'utf-8'
    filename: '/Users/hjpark/Dropbox/fastapi-basic-skeleton/logs/info/logfile.log' #maxBytes: 10485760 # 10MB,'/path/to/info.log'
  error_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: ERROR
    formatter: custom
    when: 'midnight'
    interval: 1
    backupCount: 7
    encoding: 'utf-8'
    filename: '/Users/hjpark/Dropbox/fastapi-basic-skeleton/logs/error/logfile.log' #maxBytes: 10485760 # 10MB,
  access_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: formatter_access
    when: 'midnight'
    interval: 1
    backupCount: 7
    encoding: 'utf-8'
    filename: '/Users/hjpark/Dropbox/fastapi-basic-skeleton/logs/access/logfile.log' #maxBytes: 10485760 # 10MB,
loggers:
  app:
    handlers: [console, info_file_handler, error_file_handler]
    propagate: no
  app_access:
    handlers: [access_file_handler]
    propagate: no
  root:
    level: DEBUG # ALL < DEBUG < INFO < WARN < ERROR < FATAL < OFF
    handlers: [console, info_file_handler, error_file_handler]